version: "3"

services:
  grafana:
    image: grafana/grafana:8.3.0
    volumes:
    - grafana-data:/var/lib/grafana
    - ./grafana/entrypoint.sh:/usr/local/sbin/grafana-entrypoint.sh
    - ./grafana/rootfs:/usr/local/lib/grafana/rootfs
    entrypoint: [/usr/local/sbin/grafana-entrypoint.sh]
    user: root
    ports:
    - 3000:3000
    labels:
      com.dnsdock.alias: grafana.temboardperf.docker

  loki:
    image: grafana/loki:2.4.2
    command: -config.file=/etc/loki/local-config.yaml
    labels:
      com.dnsdock.alias: loki.temboardperf.docker

  prometheus:
    image: prom/prometheus:v2.31.1
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus/import:/import
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    - "--web.console.templates=/usr/share/prometheus/consoles"
    - --log.level=debug


volumes:
  grafana-data:
