version: 2.1

jobs:
  0-docs:
    docker: [{image: "python:2.7"}]
    working_directory: ~/workspace
    steps:
    - checkout
    - run: git submodule update --init
    - run:
        name: Build documentation with Sphinx
        command: |
          pip install --upgrade -r docs/requirements-doc.txt -e .
          python setup.py --long-description | rst2html.py --verbose --halt=warning > README.html
          make -C docs/ clean html
    - store_artifacts:
        path: README.html
        destination: build/README.html

  0-rpm-centos7:
    docker: [{image: "dalibo/temboard-agent-sdk:centos7"}]
    working_directory: ~/workspace
    steps:
    - checkout
    - run: git submodule update --init
    - run:
        name: Build RPM snapshot
        command: |
          sudo yum-builddep -y packaging/rpm/temboard-agent.spec
          python setup.py sdist
          VERSION=$(python setup.py --version) ./packaging/rpm/build.sh
    - store_artifacts:
        path: ~/workspace/dist/
    - persist_to_workspace:
        root: .
        paths:
        - dist/rpm/noarch/*.rpm

  0-unit-py27:
    docker:
      - image: python:2.7
        environment: &unit_env
          TERM: linux
          TERMINFO: /etc/terminfo
    working_directory: /home/ubuntu/temboard-agent
    steps: &unit_steps
      - checkout
      - run: git submodule update --init
      - restore_cache:
          keys:
            - temboard-agent-{{ .Branch }}
            - temboard-agent-master
      - run:
          name: Python lint and tests
          command: |
            set -x
            pip install --upgrade --requirement requirement-ci.txt --editable .
            git diff --check $(git merge-base origin/master $CIRCLE_SHA1)..$CIRCLE_SHA1
            flake8 temboardagent
            python -m temboardagent.toolkit.proctitle
            pytest tests/unit/
            codecov
      - save_cache:
          key: temboard-agent-{{ .Branch }}
          paths:
            - "~/.cache/pip/"

  0-unit-py36:
    docker:
      - image: python:3.6
        environment: *unit_env
    working_directory: /home/ubuntu/temboard-agent
    steps: *unit_steps

  1-deb-stretch:
    docker: [{image: "dalibo/temboard-agent-sdk:stretch"}]
    working_directory: ~/workspace
    steps:
    - checkout
    - run: git submodule update --init
    - run:
        command: ./packaging/deb/mkdeb.sh
        environment:
          DEBFULLNAME: CircleCI
          DEBEMAIL: none@example.com
    - store_artifacts:
        path: ~/workspace/dist/
    - persist_to_workspace:
        root: .
        paths:
         - dist/*.deb

  1-func:
    parameters:
      dist:
        description: "Execution Linux distribution"
        type: enum
        enum: [centos7]
      pgversion:
        description: "PostgreSQL dotted major version"
        type: string
    docker: [image: "dalibo/temboard-agent-sdk:<< parameters.dist >>"]
    environment:
      TBD_PGVERSION: "<< parameters.pgversion >>"
    working_directory: /workspace
    steps:
    - checkout
    - attach_workspace:
        at: /workspace
    - run:
        name: Execute func tests
        command: "TBD_INSTALL_RPM=1 tests/func/run_tests_docker.sh"


workflows:
  version: 2
  pipeline:
    jobs:
    - 0-docs
    - 0-rpm-centos7
    - 0-unit-py27
    - 0-unit-py36
    - 1-deb-stretch:
        requires: [0-unit-py36]
    # Please keep tests/func/Makefile run-all test matrix sync with the
    # following.
    - 1-func:
        pgversion: "12"
        dist: centos7
        requires: [0-rpm-centos7, 0-unit-py27]
    - 1-func:
        pgversion: "11"
        dist: centos7
        requires: [0-rpm-centos7, 0-unit-py27]
    - 1-func:
        pgversion: "10"
        dist: centos7
        requires: [0-rpm-centos7, 0-unit-py27]
    - 1-func:
        pgversion: "9.6"
        dist: centos7
        requires: [0-rpm-centos7, 0-unit-py27]
