version: '2'

volumes:
  data14:
  run14:

  data12:
  run12:

  data10:
  run10:

  data96:
  run96:


services:
  ui:
    image: dalibo/temboard:8
    environment:
      # These PG* vars are for auto_configure.sh
      PGHOST: repository
      PGUSER: postgres
      PGPASSWORD: postgres
      TEMBOARD_LOGGING_LEVEL: DEBUG
    links:
      - repository
    ports:
      - "8888:8888"

  repository:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: [
      postgres,
      -c, log_connections=on,
      -c, log_statement=all,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=repository,
    ]

  instance14:
    image: postgres:14
    command: [
      postgres,
      -c, shared_preload_libraries=pg_stat_statements,
      -c, log_connections=on,
      -c, log_statement=all,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=instance14,
    ]
    ports:
      - 5432:5432
    volumes:
    - data14:/var/lib/postgresql/data
    - run14:/var/run/postgresql
    environment:
      POSTGRES_PASSWORD: postgres

  agent14:
    image: dalibo/temboard-agent:8
    volumes:
    - data14:/var/lib/postgresql/data
    - run14:/var/run/postgresql/
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - instance14:instance14.fqdn
    - ui
    environment: &agent-env
      TEMBOARD_HOSTNAME: instance14.fqdn
      TEMBOARD_UI_URL: https://ui:8888/
      TEMBOARD_UI_USER: admin
      TEMBOARD_UI_PASSWORD: admin
      TEMBOARD_LOGGING_LEVEL: DEBUG
      PGPASSWORD: postgres

  instance12:
    image: postgres:12
    ports:
      - 5433:5432
    volumes:
      - data12:/var/lib/postgresql/data
      - run12:/var/run/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    command: [
      postgres,
      -c, shared_preload_libraries=pg_stat_statements,
      -c, log_connections=on,
      -c, log_statement=all,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=instance12,
    ]

  agent12:
    image: dalibo/temboard-agent:8
    volumes:
      - data12:/var/lib/postgresql/data
      - run12:/var/run/postgresql/
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - instance12:instance12.fqdn
      - ui
    environment:
      <<: *agent-env
      TEMBOARD_HOSTNAME: instance12.fqdn

  instance10:
    image: postgres:10
    ports:
      - 5434:5432
    volumes:
      - data10:/var/lib/postgresql/data
      - run10:/var/run/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    command: [
      postgres,
      -c, shared_preload_libraries=pg_stat_statements,
      -c, log_connections=on,
      -c, log_statement=all,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=instance10,
    ]

  agent10:
    image: dalibo/temboard-agent:8
    volumes:
      - data10:/var/lib/postgresql/data
      - run10:/var/run/postgresql/
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - instance10:instance10.fqdn
      - ui
    environment:
      <<: *agent-env
      TEMBOARD_HOSTNAME: instance10.fqdn

  instance96:
    image: postgres:9.6
    ports:
      - 5435:5432
    volumes:
      - data96:/var/lib/postgresql/data
      - run96:/var/run/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    command: [
      postgres,
      -c, shared_preload_libraries=pg_stat_statements,
      -c, log_connections=on,
      -c, log_statement=all,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=instance96,
    ]

  agent96:
    image: dalibo/temboard-agent:8
    volumes:
      - data96:/var/lib/postgresql/data
      - run96:/var/run/postgresql/
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - instance96:instance96.fqdn
      - ui
    environment:
      <<: *agent-env
      TEMBOARD_HOSTNAME: instance96.fqdn
