version: '2'

services:
  centos8: &centos
    image: dalibo/buildpack-pkg:centos8
    working_dir: /workspace
    environment:
    - VERSION
    - HISTFILE=/workspace/packaging/rpm/.docker-bash-history
    volumes:
    - ../../:/workspace
    command: /workspace/packaging/rpm/build.sh

  centos7:
    <<: *centos
    image: dalibo/buildpack-pkg:centos7
