version: '2'

services:
  debian:
    image: buildpack-deps:stretch
    environment:
      # See dch(1)
      DEBFULLNAME: ${DEBFULLNAME}
      DEBEMAIL: ${DEBEMAIL}
    volumes:
    - .:/workspace
    - ../dist/:/dist
    command: /workspace/mkdeb.sh
