name: Build

on: [push, pull_request, workflow_call]

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: "16"
    - name: Install Browser packages
      run: |
        cd ui;
        npm install-clean
    - name: Build browser assets
      run: make static

    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install Python tooling
      run: pip3 install twine wheel
    - name: Build Agent & UI
      run: make dist
    - name: Check artifacts
      run: twine check --strict agent/dist/* ui/dist/*
